spring:
  application:
    name: "tech-challenge-2-fast-food-api"

  datasource:
    url: jdbc:postgresql://localhost:5446/fastfood-api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  #OpenAPI Properties
springdoc:
  api-docs:
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 8080