services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    
    command:
      - "http 8080"
      - "url=grand-vastly-jawfish.ngrok-free.app"
    environment:
      NGROK_AUTHTOKEN: ""
    ports:
      - 4040:4040

    
