apiVersion: v1
kind: Pod
metadata:
  name: fluentd-pod
  namespace: default
spec:
  containers:
    - name: fluentd-container
      image: tadrianonet/fluentd
      ports:
        - containerPort: 24224
          protocol: TCP
        - containerPort: 24224
          protocol: UDP
      volumeMounts:
        - name: fluentd-config-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
  volumes:
    - name: fluentd-config-volume
      configMap:
        name: fluentd-config